version: "3.7"
services:
  mynotes:
    image: mynotes
    container_name: mynotes
    build:
      context: ./MyNotes
    ports:
      - 80:8080
    restart: on-failure
  
  backend:
    image: mynotes-backend
    container_name: mynotes_backend
    build:
      context: ./MyNotes_backend
    ports:
      - 1323:1323
    restart: on-failure