version: "3.7"
services:
  # reverse:
  #     image: nginx:latest
  #     container_name: reverse
  #     depends_on:
  #       - mynotes
  #       - backend
  #     volumes:
  #     - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
  #     ports:
  #       - 80:80
  #       - 443:443
  #     restart: on-failure
  mynotes:
    image: mynotes
    container_name: mynotes
    build:
      context: ./MyNotes
    ports:
      - 80:8080
    restart: on-failure
  
  backend:
    image: mynotes-backend
    container_name: mynotes_backend
    build:
      context: ./MyNotes_backend
    ports:
      - 1323:1323
    restart: on-failure